name: Build and Test

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
           name: my-artifact
           path: build/reports
      - uses: actions/ckeckout@v1
        name: Git Checkout
      - uses: actions/setup-java@v1
        name: Java installieren
        with: 
          java-version: 11
      - name: Run Gradle Test
        run: ./gradlew test
      - name: Run Gradle Check
        if: success()
        run: ./gradlew check
      - name: CI-SKIP-ACTION
        uses: mstachniuk/ci-skip@v1
    
     
